services:
  postgres:
    image: postgres:16.3
    container_name: contacts-database-postgres
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - contacts-api-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: contacts-pgadmin
    ports:
      - "${PGADMIN_HOST}:${PGADMIN_PORT}"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres
    networks:
      - contacts-api-network

volumes:
  pgdata:

networks:
  contacts-api-network:
