spring:
  application:
    name: API REST Contacts
    description: Contacts REST API developed with Spring Boot

  security:
    user:
      name: admin
      password: admin

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
