spring:
  application:
    name: API REST Contacts
    description: Contacts REST API developed with Spring Boot

  security:
    user:
      name: admin
      password: admin

  datasource:
    url: jdbc:postgresql://localhost:5432/contacts
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
