services:
  ## POSTGRES ##
  postgres:
    image: postgres:16.3
    container_name: contacts-postgres
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - contacts-network
  ## PGADMIN ##
  pgadmin:
    image: dpage/pgadmin4
    container_name: contacts-pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    depends_on:
      - postgres
    networks:
      - contacts-network

volumes:
  pgdata:

networks:
  contacts-network: